services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v0.35.1
    restart: unless-stopped
    environment:
      - PUBLIC_UI_CONFIG_DISABLED
      - PUBLIC_APP_URL
      - TRUST_PROXY
    ports:
      - 80
    volumes:
      - pocket-id-data:/app/backend/data
    healthcheck:
      test: "curl -f http://localhost/health"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

volumes:
  pocket-id-data:
