services:
  trilium:
    image: zadam/trilium:latest
    ports:
      - 8080
    networks:
      - dokploy-network
    restart: always
    volumes:
      - /root/trilium-backups:/home/node/trilium-data/backup
  
networks:
  dokploy-network:
    external: true
