services:
  glance:
    image: glanceapp/glance
    volumes:
      - ../files/app/config/:/app/config
      - ../files/app/assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080
    env_file: .env